# Generated by Django 5.2.10 on 2026-01-21 09:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("collector", "0002_collectormodel_is_pickup_available"),
        ("insurance", "0001_initial"),
        ("service_charge", "0001_initial"),
        ("vehicles", "0009_alter_vehiclecapacity_capacity_value"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RenewRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Sum of Tax + Insurance + Service Charge",
                        max_digits=12,
                    ),
                ),
                ("request_date", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "collection_center",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="collector.collectormodel",
                    ),
                ),
                (
                    "insurance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="insurance.insurancemodel",
                    ),
                ),
                (
                    "service_charge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="service_charge.servicechargemodel",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="renew_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="renewals",
                        to="vehicles.uservehicle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Renew Request",
                "verbose_name_plural": "Renew Requests",
            },
        ),
    ]
