# Generated by Django 5.2.10 on 2026-01-21 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("insurance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="insurancemodel",
            name="is_active",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
