# Generated by Django 5.2.10 on 2026-01-21 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("insurance", "0002_insurancemodel_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="insurancemodel",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
