# Generated by Django 5.2.10 on 2026-01-21 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_charge", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicechargemodel",
            name="fiscal_year",
            field=models.CharField(max_length=100),
        ),
    ]
