# Generated by Django 5.2.10 on 2026-01-12 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("collector", "Collector"),
                    ("user", "User"),
                ],
                max_length=20,
            ),
        ),
    ]
