# Generated by Django 5.2.10 on 2026-01-13 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_role"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="role",),
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
