# Generated by Django 5.2.10 on 2026-01-13 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_remove_user_role_user_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_collector",
            field=models.BooleanField(default=False),
        ),
    ]
