# Generated by Django 5.2.10 on 2026-01-22 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("collector", "0002_collectormodel_is_pickup_available"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="collectormodel", name="collection_center_address",
        ),
        migrations.RemoveField(
            model_name="collectormodel", name="collection_center_name",
        ),
        migrations.RemoveField(
            model_name="collectormodel", name="collection_center_number",
        ),
        migrations.RemoveField(
            model_name="collectormodel", name="is_pickup_available",
        ),
    ]
