# Generated by Django 5.2.10 on 2026-01-22 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collector", "0003_remove_collectormodel_collection_center_address_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CollectionCenterModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=100)),
                ("phone_number", models.CharField(max_length=100)),
                ("is_pickup_available", models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name="collectormodel",
            name="collection_center",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="manager",
                to="collector.collectioncentermodel",
            ),
        ),
    ]
