# Generated by Django 5.2.10 on 2026-01-14 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="vehiclecapacity", name="vehicle_capacity",),
        migrations.AddField(
            model_name="vehiclecapacity",
            name="capacity_value",
            field=models.IntegerField(
                default=0, help_text="CC for fuel or kW for electric"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="vehicletax",
            name="vehicle_capacity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tax_rules",
                to="vehicles.vehiclecapacity",
            ),
        ),
    ]
