# Generated by Django 5.2.10 on 2026-01-14 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0002_remove_vehiclecapacity_vehicle_capacity_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="vehicletax", name="max_capacity",),
        migrations.RemoveField(model_name="vehicletax", name="min_capacity",),
    ]
