# Generated by Django 5.2.10 on 2026-01-16 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0003_remove_vehicletax_max_capacity_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="uservehicle",
            options={
                "verbose_name": "User Vehicle",
                "verbose_name_plural": "User Vehicle's",
            },
        ),
        migrations.AlterModelOptions(
            name="vehiclecapacity",
            options={
                "verbose_name": "Vehicle Capacity",
                "verbose_name_plural": "Vehicle Capacities",
            },
        ),
        migrations.AlterModelOptions(
            name="vehiclefueltype",
            options={
                "verbose_name": "Vehicle Fuel Type",
                "verbose_name_plural": "Vehicle Fuel Types",
            },
        ),
        migrations.AlterModelOptions(
            name="vehicleownership",
            options={
                "verbose_name": "Vehicle OwnerShip",
                "verbose_name_plural": "Vehicle Ownerhship's",
            },
        ),
        migrations.AlterModelOptions(
            name="vehicletax",
            options={
                "verbose_name": "Vehicle Tax",
                "verbose_name_plural": "Vehicle Taxes",
            },
        ),
        migrations.AlterModelOptions(
            name="vehicletype",
            options={
                "verbose_name": "Vehicle Type",
                "verbose_name_plural": "Vehicle Types",
            },
        ),
    ]
