# Generated by Django 5.2.10 on 2026-01-16 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0004_alter_uservehicle_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="uservehicle",
            name="vehicle_number",
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
