# Generated by Django 5.2.10 on 2026-01-16 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0005_uservehicle_vehicle_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uservehicle",
            name="engine_capacity",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="vehicles.vehiclecapacity",
            ),
        ),
        migrations.AlterField(
            model_name="vehiclecapacity",
            name="capacity_value",
            field=models.DecimalField(
                decimal_places=2,
                help_text="CC for fuel, kW for electric",
                max_digits=10,
            ),
        ),
    ]
