# Generated by Django 5.2.10 on 2026-01-16 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0006_alter_uservehicle_engine_capacity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehiclecapacity",
            name="capacity_value",
            field=models.IntegerField(),
        ),
    ]
