# Generated by Django 5.2.10 on 2026-01-16 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0007_alter_vehiclecapacity_capacity_value"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="uservehicle",
            options={
                "verbose_name": "User Vehicle",
                "verbose_name_plural": "User Vehicles",
            },
        ),
        migrations.AlterModelOptions(
            name="vehicleownership",
            options={
                "verbose_name": "Vehicle Ownership",
                "verbose_name_plural": "Vehicle Ownerships",
            },
        ),
        migrations.AlterField(
            model_name="vehiclecapacity",
            name="capacity_value",
            field=models.IntegerField(help_text="CC for fuel, kW for electric"),
        ),
    ]
