# Generated by Django 5.2.10 on 2026-01-16 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0008_alter_uservehicle_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehiclecapacity",
            name="capacity_value",
            field=models.CharField(max_length=50),
        ),
    ]
